### ISSUE TITLE
pointer-constraints' motionnotify() no longer permits merge with upstream

### ISSUE THREAD

**Issue by fauxmight** [sevz17/dwl#16]
## Info
dwl's commit: b5776e5180010ead5232efb36b2490f4fc9e1366
wlroots version: 0.15.1
## Description
The pointer-constraints branch here and mainline now differ significantly in the arguments to motionnotify()

I am not immediately clear on how to resolve this or if this is a substantial, non-trivial matter to properly merge.

**Comment by sevz17** [comment]
Yes, that was the most factible solution I found, in a internal call of motionmotify() the arguments
should be `motionnotify(0, NULL, 0, 0, 0, 0)`

**Comment by fauxmight** [comment]
This will be obsolete when  [djpohly/dwl:#334](https://github.com/djpohly/dwl/pull/334) and #19 are merged.
