### ISSUE TITLE
2023-02-13 patch updates

### ISSUE THREAD

**Issue by fauxmight** [sevz17/dwl#24]
@sevz17 I have rebased the following patches since your updates today to upstream (djpohly):

pointer-constraints
smartborders
numlock/capslock
autostart

I have tested with all of the above rebased patches applied and found no problems. If you find anything incorrect in the rebasing, please let me know.

**Comment by fauxmight** [comment]
~I am updating the wiki entries for those patches now.~
Wiki pages are updated *except* `pointerConstraints` because that one points to the Palanix patch.

**Comment by sevz17** [comment]
autostart patch required more changes, it's updated now.

pointer constraints is called `sway-pointer-constraints`.

The other ones look great.
