### ISSUE TITLE
Updated branches/patches 2023-05-26

### ISSUE THREAD

**Issue by fauxmight** [sevz17/dwl#26]
@sevz17 I have rebased the following branches on djpohly/main commit 0729f18. ALL of these were clean rebases with no manual intervention required. I have updated the wiki pages for each patch with today's date (2023-05-26):

- pointer-constraints
- autostart
- numlock/capslock
- smartborders

If anything looks out of place, please let me know. Otherwise, feel free to close this "issue."

**Comment by sevz17** [comment]
All seems good.
Thanks!
