### ISSUE TITLE
Idle "hint" status, systemd-logind and idle-inhibitor

### ISSUE THREAD

**Issue by fauxmight** [sevz17/dwl#3]
I have merged both your idle-inhibitor branch and your input-inhibitor branch and find that this works nicely with swayidle/swaylock allowing automated timeout locking of an idle dwl session. (**Thank you!**)

However, if I set "IdleAction=suspend" in logind.conf (with a systemd machine), reboot the machine (or restart systemd-logind) and start a dwl session, dwl never suspends.

A login at TTY will suspend with the above set, but although swayidle is recognizing idle vs idle-inhibited state, logind does not when dwl is running.

I suspect this has something to do with "idle hinting," but don't know enough to dig further. Reading through the commits in the idle-inhibitor branch, I cannot tell whether this is an expected state of affairs or not.

If this is a trivial matter, point me in the right direction; I am happy to work on it.
If it is expected behaviour, let me know and I'll close the issue.

**Comment by sevz17** [comment]
> However, if I set "IdleAction=suspend" in logind.conf (with a systemd machine), reboot the machine (or restart systemd-logind) and start a dwl session, dwl never suspends.  

I didn't consider logind or elogind when I wrote that


> If this is a trivial matter, point me in the right direction; I am happy to work on it.

Can you try it in sway and say me if it works?
If it works in sway and doesn't add much code, I think we can implement it

**Comment by fauxmight** [comment]
This issue is mistaken.

With another application (`swayidle`, for example) setting "IdleHint" this works correctly.
Sway works in the same fashion and does NOT set IdleHint itself but depends upon `swayidle` or other applications to handle IdleHint.
