### ISSUE TITLE
Many application clippings have an abnormal window size

### ISSUE THREAD

**Issue by DreamMaoMao** [sevz17/dwl#30]
## Info
dwl version:wlroots-next with scence-clip patch
wlroots version:lastest source code with scence-clip patch

There's a big gap between the surface and the border:

![2023-10-17_08-25](https://github.com/sevz17/dwl/assets/30348075/7f9c649d-1230-49d1-a26c-94a5807ad1c0)

Abnormal application(swappy,eog,gdm-setting,gnome-system-monitor)

**Comment by sevz17** [comment]
Ah right, yeah, I'm aware of that (I also use the patch), unfortunately I have other things to do and this is not a priority (but I'll fix it, I promise).

**Comment by DreamMaoMao** [comment]
By the way, set the environment variable of these app to x11 to make them work in xwayland mode. The window size will return to normal,

it means that the clip patch will only make some wayland app window abnormal.

**Comment by sevz17** [comment]
@DreamMaoMao, I think I fixed the issue, can you test the new version?

**Comment by DreamMaoMao** [comment]
It doesn’t work properly, when I start the app with an abnormal cut size that I mentioned before (like gnome-system-monitor), dwl will crash directly, and when I start the app with a normal cut size, it run normally

**Comment by DreamMaoMao** [comment]
![image](https://github.com/sevz17/dwl/assets/30348075/effd702a-3cb6-4048-9173-268e27bbcac3)
it seemed that coredump didn't record anything useful

**Comment by DreamMaoMao** [comment]
[coredump_dwl.log](https://github.com/sevz17/dwl/files/13233008/coredump_dwl.log)

**Comment by DreamMaoMao** [comment]
![image](https://github.com/sevz17/dwl/assets/30348075/c4a94470-e5a7-4f31-90b2-086cbef78dd5)
gdb debug message

**Comment by sevz17** [comment]
@DreamMaoMao, I'm sorry I forgot to reply.

In my machine if I set `borderpx` to at least 4 the assertion does no fail, I guess this is something wrong on the wlroots side.

**Comment by DreamMaoMao** [comment]
Unfortunately

**Comment by DreamMaoMao** [comment]
https://github.com/sevz17/dwl/assets/30348075/4a9baa28-51f6-4c2a-ac67-11d7ca14631b

I see that wlroots has  merge
the clip patch and it seems that the issue has been resolved
