### ISSUE TITLE
[Pointer-constraints patch] Cursor stay constrained even if client is not focused.

### ISSUE THREAD

**Issue by korei999** [sevz17/dwl#31]
## Info
dwl version: 0.4
wlroots version: 0.16.2-2
## Description
So the problem with functions like `glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_DISABLED);` or `SDL_SetRelativeMouseMode(SDL_TRUE);`. I see the same behavior with steam/wine games either.
Cursor keep being locked even if client is not focused. So the relative mode works properly inside sdl or glfw or some other window, but it seems that constraints are not being destroyed after focusing other client or going to another tag, and cursor remains constrained.
dwl -d log only shows this while toggling between tags
```
00:00:11.229 [DEBUG] [types/wlr_pointer_constraints_v1.c:242] new locked_pointer 0x5597235fdfa0 (res 0x559723526a80)
00:00:11.229 [DEBUG] [types/wlr_pointer_constraints_v1.c:343] constrained 0x5597235fdfa0
00:00:12.785 [DEBUG] [types/wlr_idle.c:183] Enabling idle timers for all seats
00:00:13.089 [DEBUG] [types/wlr_idle.c:183] Disabling idle timers for all seats
00:00:13.419 [DEBUG] [types/wlr_idle.c:183] Enabling idle timers for all seats
00:00:13.625 [DEBUG] [types/wlr_idle.c:183] Disabling idle timers for all seats
00:00:13.903 [DEBUG] [types/wlr_idle.c:183] Enabling idle timers for all seats
00:00:14.123 [DEBUG] [types/wlr_idle.c:183] Disabling idle timers for all seats
00:00:14.389 [DEBUG] [types/wlr_idle.c:183] Enabling idle timers for all seats
```
[Video example.](https://www.youtube.com/watch?v=RZ-eZsaHlEk)

**Comment by sevz17** [comment]
Hi, this is to let you know that although I haven't look at this, you are not being ignored.

Given the migration to codeberg I re-reported this here: https://codeberg.org/sevz/dwl/issues/1
