### ISSUE TITLE
Disable or at least turn off numlock.

### ISSUE THREAD

**Issue by lidgnulinux** [sevz17/dwl#7]
How to disable / turn off numlock when launch dwl?

**Comment by fauxmight** [comment]
In THIS (Sevz17's) fork, there is a [numlock/capslock branch](https://github.com/Sevz17/dwl/tree/numlock/capslock) that likely accomplishes what you are after.


A patch link exists [here](https://github.com/djpohly/dwl/compare/main...Sevz17:numlock/capslock.patch).

It comes from the [patches page](https://github.com/djpohly/dwl/wiki/Patches) on the wiki at the main repo:

**Comment by sevz17** [comment]
sorry for the long delay to reply.

just to complete the fauxmight's reply, if you use the 'custom' branch, then you have to edit `createkeyboard()` because it's harcoded to enable numlock by default

**Comment by lidgnulinux** [comment]
Thanks @fauxmight and @sevz17 . I'll try it.
